spring:
  data:
    mongodb:
      database: devs_skills
redis:
  caches:
    - name: employee_id
      expiry: 1800

---

spring:
  profiles: docker
  data:
    mongodb:
      host: mongodb

---

spring:
  profiles: cloud